# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-13 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonnalInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nom')),
                ('last_name', models.CharField(max_length=30, verbose_name='Pr\xe9nom')),
            ],
        ),
    ]
