# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-17 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_auto_20170917_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnalinformation',
            name='facebook',
            field=models.URLField(null=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='personnalinformation',
            name='linkedin',
            field=models.URLField(null=True, verbose_name='LinkedIn'),
        ),
        migrations.AddField(
            model_name='personnalinformation',
            name='twitter',
            field=models.URLField(null=True, verbose_name='Twitter'),
        ),
        migrations.AddField(
            model_name='personnalinformation',
            name='website',
            field=models.URLField(null=True, verbose_name='Site web'),
        ),
    ]
