# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-17 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0005_auto_20170917_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnalinformation',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Adresse email'),
        ),
    ]
