# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-17 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0006_auto_20170917_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnalinformation',
            name='adr_country',
        ),
        migrations.RemoveField(
            model_name='personnalinformation',
            name='adr_street',
        ),
        migrations.RemoveField(
            model_name='personnalinformation',
            name='adr_zipcode',
        ),
        migrations.RemoveField(
            model_name='personnalinformation',
            name='bithdate',
        ),
        migrations.AddField(
            model_name='personnalinformation',
            name='position',
            field=models.CharField(default='Undifined', max_length=50, verbose_name='Job actuel'),
            preserve_default=False,
        ),
    ]
