# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 17:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0007_auto_20170917_1906'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PersonnalInformation',
            new_name='PersonalInformation',
        ),
    ]
