# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0008_auto_20170918_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinformation',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='twitter',
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='github_username',
            field=models.CharField(max_length=30, null=True, verbose_name="Nom d'utilisateur Github"),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='twitter_username',
            field=models.CharField(max_length=30, null=True, verbose_name="Nom d'utilisateur Twitter"),
        ),
    ]
