# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 17:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0011_personalinformation_career_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Intitulé du diplôme')),
                ('institution', models.CharField(max_length=30, verbose_name="Institution d'obtention")),
                ('dates', models.CharField(max_length=30, verbose_name='Année de début et de fin')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.PersonalInformation')),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name="Nom de l'intérêt")),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.PersonalInformation')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Langue')),
                ('level', models.CharField(max_length=30, verbose_name='Niveau dans la langue')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.PersonalInformation')),
            ],
        ),
    ]
