# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 17:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0013_experience_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Domaine de compétence')),
                ('level', models.PositiveIntegerField(verbose_name='Pourcentage de compétence')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.PersonalInformation')),
            ],
        ),
    ]
