# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 19:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0014_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date de visite')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.PersonalInformation')),
            ],
        ),
    ]
