# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0016_resumepartview'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinformation',
            name='auth_for_stats',
            field=models.BooleanField(default=False, verbose_name='Authentification pour les statistiques'),
        ),
    ]
