# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 18:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0019_personalinformation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinformation',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cv.ResumeUser', verbose_name='Utilisateur lié'),
        ),
    ]
