# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0021_remove_resumeuser_have_limitations'),
    ]

    operations = [
        migrations.AddField(
            model_name='limitationpolicy',
            name='policy_name',
            field=models.CharField(default='Police par défaut', max_length=30, verbose_name='Nom de la police'),
            preserve_default=False,
        ),
    ]
