# Generated by Django 2.0 on 2018-04-06 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0022_limitationpolicy_policy_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limitedresumeuser',
            name='limitation_policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cv.LimitationPolicy', verbose_name='Politique de limitation'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cv.ResumeUser', verbose_name='Utilisateur lié'),
        ),
    ]
